services:
  nginx:
    image: nginx:mainline-alpine-slim
    container_name: nginx
    volumes:
      - ./htdocs:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4001:80"
    depends_on:
      - php
    networks:
      - back
      - front

  mysql:
    image: mysql:8.4.1
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    restart: unless-stopped
    networks:
      - back

  php:
    image: php:8.3.22-fpm-alpine
    container_name: php
    volumes:
      - ./htdocs:/var/www/html
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin
    ports:
      - "6001:80"
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - back
      - front

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  mysql_data:

networks:
  back:
    driver: bridge
  front:
    driver: bridge
